### ISSUE TITLE
To-do's for POC

### ISSUE THREAD

**Issue by rafeymalik1** [russellrd/realm#82]
POC is due on Monday, Nov 11 3:45pm to 4:00pm.

**Important Notes:**
*Use Unity version 6000.0.25f1
Libraries _(Add here)_ : 

To-do:
- [ ] Setup template project in unity

1. User scans object, obtaining a 3D model they can place. (Abdul & Avanish)
   - [x] Be able to enter the object scanning workflow
   - [ ] Object scanning workflow:
      - [x] Select 2D or 3D object
      - [ ] Identify and start scanning an object in real space
      - [ ] Present some indication of the progress of the object scan (separate render, or highlight scanned portion)
      - [x] Give the user the option to finish scanning
      - [x] Present user a preview of their final object, give them option to re do the scan or confirm completion

3. User virtually places said object in their surroundings. (Rafey & Russell)
   - [ ] Have an inventory of 5 objects of unique shapes.
   - [ ] Be able to store objects and metadata
   - [ ] Be able to select desired object via interface
   - [ ] Object placement workflow:
     - [ ] Object can be viewed in the 3D space before placement
     - [ ] Object can be scaled.
     - [ ] Object can be moved
     - [ ] Display red/green feedback to indicate if the object can be placed based on its size and position.
     - [ ] Confirm/cancel object placement
   - [ ] Have the object interaction panel viewable (e.g. react, delete, edit). --> Only the front end for react and edit, but actually implement delete.
4. User leaves the area, returns, and can see the object they placed in the correct position. (Rafey & Russell)
   - [ ] Verify that the object which has been placed has its absolute position within 5cm (or some threshold) of its original spot, after leaving the app and reopening (GPS AR).
